version: '2'
services:
    cavavin-app:
        image: cavavin
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cavavin-postgresql:5432/cavavin
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cavavin-postgresql:
        extends:
            file: postgresql.yml
            service: cavavin-postgresql
